import Head from 'next/head';

import { Nunito } from '@next/font/google';

import { useQuery } from '@apollo/client';

import QUERY_POSTS from '@/graphql/queries/Posts.graphql';

import PostsList from '@/components/PostsList/PostsList.component';

// eslint-disable-next-line new-cap
const fontNunito = Nunito({ subsets: ['latin'] });

function Home() {

  const { data, fetchMore } = useQuery(QUERY_POSTS);

  const handleMore = () => {

    fetchMore({
      variables: {
        after: data.posts.pageInfo.endCursor,
      },
    });

  };

  return (
    <>
      <Head>
        <title>
          Product Hunt
        </title>

        <meta
          content="Generated by create next app"
          name="description"
        />

        <meta
          content="width=device-width, initial-scale=1"
          name="viewport"
        />
      </Head>

      <main className={fontNunito.className}>
        {
          data && data.posts
            ? (
              <PostsList
                {...data.posts}
                onLoadMore={handleMore}
              />
            )
            : null
        }
      </main>
    </>
  );

}

export default Home;

