import Head from 'next/head';

import { useQuery } from '@apollo/client';

import QUERY_POSTS from '@/graphql/queries/Posts.graphql';

import PostsList from '@/components/PostsList/PostsList.component';

const RANKING_QUERY = { variables: { order: 'RANKING' } };

function Home() {

  const { data, fetchMore } = useQuery(QUERY_POSTS, RANKING_QUERY);

  const handleMore = () => {

    fetchMore({
      variables: {
        ...RANKING_QUERY.variables,
        after: data.posts.pageInfo.endCursor,
      },
    });

  };

  return (
    <>
      <Head>
        <title>
          Product Hunt
        </title>

        <meta
          content="Generated by create next app"
          name="description"
        />

        <meta
          content="width=device-width, initial-scale=1"
          name="viewport"
        />
      </Head>

      {
        data && data.posts
          ? (
            <PostsList
              {...data.posts}
              onLoadMore={handleMore}
            />
          )
          : null
      }
    </>
  );

}

export default Home;

