import Head from 'next/head';

import { QueryHookOptions, useQuery } from '@apollo/client';

import QUERY_POSTS from '@/graphql/queries/Posts.graphql';

import PostsList from '@/components/PostsList/PostsList.component';

const NEWEST_QUERY: QueryHookOptions = {
  fetchPolicy: 'cache-and-network',
  initialFetchPolicy: 'no-cache',
  variables: { order: 'NEWEST' },
};

function Newest() {

  const { data, fetchMore } = useQuery(QUERY_POSTS, NEWEST_QUERY);

  const handleMore = () => {

    fetchMore({
      variables: {
        ...NEWEST_QUERY.variables,
        after: data.posts.pageInfo.endCursor,
      },
    });

  };

  return (
    <>
      <Head>
        <title>
          Product Hunt
        </title>

        <meta
          content="Generated by create next app"
          name="description"
        />

        <meta
          content="width=device-width, initial-scale=1"
          name="viewport"
        />
      </Head>

      {
        data && data.posts
          ? (
            <PostsList
              {...data.posts}
              onLoadMore={handleMore}
            />
          )
          : null
      }
    </>
  );

}

export default Newest;

